# Site settings
title: Arquitecturas Concurrentes
header-img: img/home-bg.jpg
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://arquitecturas-concurrentes.github.io/"
github_username: "arquitecturas-concurrentes"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: blog/page:num
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
