# Site settings
title: Arquitecturas Concurrentes
header-img: img/home-bg.jpg
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://arquitecturas-concurrentes.github.io/"
github_username: "arquitecturas-concurrentes"

# Build settings
permalink: pretty
paginate: 5
paginate_path: blog/page:num
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: ['jekyll-paginate', 'rouge', 'kramdown']
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge