# Site settings
title: Arquitecturas Concurrentes
header-img: img/home-bg.jpg
description: "Materia Electiva de 5to año de la universidad UTN regional Buenos Aires."
baseurl: ""
url: "http://arquitecturas-concurrentes.github.io/"
github_username: "arquitecturas-concurrentes"

# Build settings
permalink: pretty
paginate: 5
paginate_path: blog/page:num
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: ['jekyll-paginate', 'rouge', 'kramdown']
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge